### ISSUE TITLE
P8 Closures

### ISSUE THREAD

**Issue by MichaelMeinberg** [MakeSchool-Tutorials/Makestagram-Swift#40]
I would recommend that you change the code to have the non-trailing format first, and explain the trailing to them rather then the way it is now (which is the opposite). I think the non-trailing format is clearer, but because you have the 'callback' argument name in it.

**Comment by dionlarson** [comment]
Wrong repository. Already planning to add more info on closures.

**Comment by danielhaaser** [comment]
This is the correct repository and is a somewhat decent argument I think - the way closures are introduced in Makestagram is confusing because they're not explained super well (though this is very difficult without examples, hopefully closures playground will help). But also they're introduced both with standard syntax and trailing format, which is confusing.

**Comment by dionlarson** [comment]
The correct repository is https://github.com/MakeSchool-Tutorials/Makestagram-Swift-V2
